import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import { ApolloWrapper } from "@/lib/apolloWrapper";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import ToggleMode from "@/components/ToggleMode";
import Dashboard from "./dashboard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <ApolloWrapper>
        <body className={inter.className}>
          <SessionProvider session={session}>
            <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                {" "}
                {children}
                {/* <Dashboard /> */}
              </ThemeProvider>
            </div>
          </SessionProvider>
        </body>
      </ApolloWrapper>
    </html>
  );
}
